### ISSUE TITLE
[BUG] Cant link journal entry with token. Only shows token name and empty text

### ISSUE THREAD

**Issue by GeorgeDittmar** [jendave/token-note-hover#12]
**Module Version:** v2.1.8

**Describe the bug**
This could be user error but its not clear to me how to associate token notes with this module or how they link. It appears to only show and empty dialog box when I hover and not the journal entry I linked with the token like I thought would happen. Tried to reinstall but no dice. Is there a step I might be missing or is this a bug? 

**Expected behavior**
Notes from journal for a given token.

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 
v12

**Game System:** 
DnD 5E

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by jendave** [comment]
Hi. I have released a new version (2.1.9) that fixes some issues with the D&D 5E Token notes. I have also added documentation that explains the location of each note on the actor tokens. https://foundryvtt.com/packages/token-note-hover

Please update and let me know if this helps. Thanks
