### ISSUE TITLE
[BUG] PF2e Support not working

### ISSUE THREAD

**Issue by ChasarooniZ** [jendave/token-note-hover#8]
Lists as supports PF2e, however it isn't a system it has a relationship with so it isn't enableable in a pf2e world

**Comment by jendave** [comment]
I had updated the documentation prior to the release. I have just released v2.0.1 which has the relationsip in the module.json. Please update to the latest version of Token Note Hover. Thanks,

**Comment by ChasarooniZ** [comment]
yeah it now lets me enable it, so fixed!

**Comment by ChasarooniZ** [comment]
Also love the module, this will save me a ton of time in game!

**Comment by jendave** [comment]
That's great to hear! I tried to keep the functionality very straight-forward and simple, but let me know if anything needs to be added or tweaked. Thanks!

**Comment by ChasarooniZ** [comment]
Is there any reason for the zoom and pan options requirement for this module?

**Comment by jendave** [comment]
Normally, Foundry zooms around the center of the screen. The Zoom/Pan allows you to zoom around your cursor. Typically that means you can zoom around the token you are pointing to.
